version: 0.0.5.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{appveyor_repo_branch}"

configuration: Release

install:
  - ps: .\scripts\install.ps1

before_build:
  - nuget restore source\IdentityServer.v3.MongoDb.sln

build:
  project:  Source\IdentityServer.v3.MongoDb.sln

after_test: 
  - ps: .\scripts\packagenuget.ps1

artifacts: 
  - path: Source\Core.MongoDb\bin\Release\IdentityServer.Core.MongoDb.dll
    name: IdentityServer.Core.MongoDb.dll
  - path: Source\IdentityServer.MongoDb.AdminModule\bin\Release\IdentityServer.MongoDb.AdminModule.dll
    name: IdentityServer.MongoDb.AdminModule.dll
  - path: '*.nupkg'

deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key: 
    secure: k1FLU1hRZEYRxDnZ8wS99CqjVgzr2nVFLnwhpYZ0ChTSDEJ5L5yJT7DgErg7vlG/
  artifact: /.*\.nupkg/